[package]
name = "oramon-collector"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
oramon-core   = { path = "../oramon-core" }
oramon-oracle = { path = "../oramon-oracle" }

tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
